### PR TITLE
Fix return of super.static if val false (fix #50)

### LINKED ISSUE #50: There's a bug in line 82
`setmetatable(aClass.static, { __index = function(_,k) return rawget(dict,k) or super.static[k] end })`

if rawget(dict,k) is a boolean value and its value is false, it went wrong.
so you should change the **or** expression to **if/else**

### PR DESCRIPTION
**Pull request by qaisjp**

### CODE REVIEW

**Comment by kikito** [comment]
hi, thanks for the PR, but I think you used C syntax for your `if` :D In Lua we use `then ... end` instead (I also do this from time to time)

**Comment by qaisjp** [comment]
Hahaha oh dear :D

**Comment by qaisjp** [comment]
ping

**Comment by kikito** [comment]
Apologies for not doing this sooner. Thanks

**Pull request merged**
