### PR TITLE
Lua 5.3 metamethods

### PR DESCRIPTION
**Pull request by kikito**

### CODE REVIEW

**Comment by mpeterv** [comment]
@kikito if this helps, the metamethod stubs probably should not raise error on missing metamethod if it's `__gc`, because it can be called involuntary on GC cycle. I.e. this fixes the busted error:

```diff
--- a/middleclass.lua
+++ b/middleclass.lua
@@ -64,8 +64,11 @@ end
 local function _createLookupMetamethod(aClass, name)
   return function(...)
     local method = aClass.super[name]
-    assert( type(method)=='function', tostring(aClass) .. " doesn't implement metamethod '" .. name .. "'" )
-    return method(...)
+    if type(method) == 'function' then
+      return method(...)
+    else
+      assert( name == '___gc', tostring(aClass) .. " doesn't implement metamethod '" .. name .. "'" )
+    end
   end
 end
```

Also, perhaps `__mode` and `__metatable` shouldn't be stubbed. They are not really metamethods but just special fields in the metatable (metafields?). E.g. with this patch `getmetatable(object)` returns the stub for `__metatable` instead of the real metatable.

**Comment by kikito** [comment]
Hi @mpeterv, thanks for your comments.

You are completely right in both accounts. I will fix the `__shl` and deactivating the stubbing of `__gc` is my plan; I want to transform the `__metamethods` table into a hash with truthy/false values indicating whether the method in question should be stubbed.

I just need to find some time to do it - I don't have Lua 5.3 installed locally so I must rely on travis executing the tests, which is a hassle. But thanks!

**Comment by mpeterv** [comment]
> I don't have Lua 5.3 installed locally so I must rely on travis executing the tests, which is a hassle.

@kikito it's a shameless plug, but you could use [hererocks](https://github.com/mpeterv/hererocks) to run tests using versions of Lua other than the global one. E.g. assuming you have Python's package manager pip you could just run

    sudo pip install hererocks
    hererocks here -l 5.3 -r ^
    here/bin/luarocks install busted
    here/bin/busted spec

**Comment by kikito** [comment]
I have not forgotten about this. That python magic certainly looks very intriguing. I have been looking for a way to make testing lua in travis easier, and your package might just be it. I won't do it just now, but I want you to know that it is in my radar and I will absolutely test it. Thanks for sharing!

**Comment by kikito** [comment]
@mpeterv hererocks is just what I was looking for, thanks <3

**Pull request merged**
